package common.viwes;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 05 15:37:23 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DummyVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Dummy,
        UnitCode,
        GlType,
        FinYear,
        fromDate,
        toDate,
        GlCode,
        LOC,
        Customer,
        ItemCd,
        GroupCd,
        SubGroupCd,
        LocWip,
        INC_CAN,
        DocType,
        DAFILTER,
        PoNo,
        ChallanType,
        CollectionCust,
        BankReconcilation_GL,
        Debit_Credit_note_Type,
        AsmblyJC_Prod_Cd,
        Asmbly_JCNo,
        BOM_Product_CD,
        WIPLgr_PrcssFilter,
        WIPLgr_ItemFilter,
        BOMTree_BOM_Prd_cd,
        BOMTree_Batchqty,
        RequiredBatch,
        PartNameFilter,
        Assembly_prd_dtl_prdcd,
        BMR_BT_BOMITEM,
        Non_Moving_Item_prd,
        Non_Moving_Item_Day,
        SRVRejectionRegister_RepType,
        StockAdjustment_PartName,
        PndingSrvForQcVendorCd,
        Jobworkregister_JWNO,
        PurchaseIndent_ApprovedBy,
        NatureOfPurchase,
        InterUnit,
        Pending_Purchase_Order_ValidTill,
        Pending_Purchase_Order_AppStatus,
        ProcsInspction_ProdCD,
        ProcsInspction_Process,
        QualityInProcess_ITEMFILTER,
        ItemDetailAfterQcItemCd,
        PendingBMRForQC_BatchFilter,
        LV_p1,
        LV_p2,
        LV_p3,
        LV_p4,
        LV_p5,
        LV_p6,
        SubLedger_UnitCode,
        SubLedgerNameFilter,
        Challan_No,
        PendingToD28_ItemCode,
        WarehouseName,
        DailyInvoice_InvoiceNo,
        InvoiceWiseSale_ItemName,
        InterUnitTransit_UnitCode,
        EInvoice_InvoiceNo,
        ItemWiseSale_InvoiceType,
        ItemWiseSale_StockType,
        ItemWiseSale_ProductCode,
        TRFRegister_ProductFilter,
        BatchwiseBMRConsumption_partCode,
        BatchwiseBMRConsumption_BatchNo,
        BatchWiseBPRConsumption_ProductName,
        BatchWiseBPRConsumption_BatchNo,
        PendingJobcardForApproval_Approved,
        LotStock_ItemType,
        ProductShortageandBatch_ProductName,
        ItemWiseTotalInventory_ProductCd,
        RequisitionSlipRegister_ReqTypeFilter,
        ARNumberAgainstMRNITEM_ItemName,
        GoodsinTransit_ChallanNo,
        SRVDetail_ApproveFilter,
        SRVDetail_Statusfilter,
        SRVDetail_LocationFilter,
        DailyStockStatement_LocationFilter,
        ShortExcessRegister_RepType,
        MonthlyPackingSummary_CategaryCd,
        AR_Unit,
        AR_Location,
        AR_GROUP,
        AR_ITEM,
        AR_AR_NO,
        AR_SubGroup,
        rep_type,
        Bulk_IssueSlipNo,
        Bulk_ItemName,
        UnitVVO1,
        GlCodeVVO2,
        LocVVO1,
        CustomerVVO1,
        GroupCodeVVO1,
        SubGroupCodeVVO1,
        LocProdWipVVO1,
        SaleregisterDetailVO1,
        TestVVO1,
        CancelationVVO1,
        FinYearVVO1,
        ItemCodeVVO3,
        DocTypeStaticvalueVVO1,
        PONoFILTERVVO1,
        ChallanTypeFilterVVO1,
        CollectionCustomerVVO1,
        BankReconciliationGLVVO1,
        DebitCreditNote_typeVVO1,
        YES_NO_BOTHVVO1,
        GL_TypeVO1,
        AssemblyJobCard_prodcodeVVO1,
        AssemblyJobCard_JCNoVVO1,
        BOM_PRD_CDVVO1,
        WIPLgr_ProcessFilterVVO1,
        WIPLgr_ItemFilterVVO1,
        BOMTree_PRDCDVVO1,
        Bom_batch_qtyVVO1,
        BOMTree_batch_qtyVVO1,
        PartNameFilterVVO1,
        Assembly_prd_dtl_Prdcd1,
        BMR_BT_BOMITEMVVO1,
        DA_Filter2,
        Non_Moving_Item_ProductVVO1,
        SRVRejectionRegister_REPTYPEVO1,
        StockAdjustment_PartNameVVO1,
        PndingSRVForQcVendorCdVVO1,
        JobworkRegisterJWNOVVO1,
        PurchaseIndent_ApprovedByVVO1,
        Prchse_Rgistr_NatureOfPurchaseVO1,
        Prchse_Rgistr_INTER_UNIT1,
        PendingPurchaseOrderValidTillVVO1,
        PendingPurchaseOrderAppStatusVVO1,
        ProcsInspctionProductCodeVVO1,
        ProcsInspctionProcessVVO1,
        QualityInProcess_ITEMFILTERVVO1,
        ItemDetailAfterQC_ItemCd1,
        PendingBMRForQC_BatchFilterVVO1,
        SubLedger_UnitVVO1,
        SubLedgerNameFilterVVO1,
        Challan_NoVVO1,
        PendingToD28_ItemCodeVVO1,
        STOFromSale_WarehouseName1,
        DailyInvoice_InvoiceNoVVO1,
        InvoiceWiseSale_ItemNameVVO1,
        InterUnitTransitReport_UnitCodeVVO1,
        EInvoice_InvoiceNoVVO1,
        ItemWiseSale_InvoiceTypeVVO1,
        ItemWiseSale_StockTypeVVO1,
        ItemWiseSale_ProductCodeVVO1,
        TRFRegister_ProductFilterVO1,
        BatchwiseBMRConsumption_parCodeVVO1,
        BatchwiseBMRConsumption_BatchNoVVO1,
        BatchWiseBPRConsumption_ProductNameVVO1,
        BatchWiseBPRConsumption_BatchNoVVO1,
        PendingJobcardForApproval_ApprovedVVO1,
        LotStock_ItemTypeVVO1,
        ProductShortageandBatchReportVO1,
        ProductShortageandBatch_ProductNameVVO1,
        ItemWiseTotalinventory_ProductCdVVO1,
        RequisitionSlipRegister_ReqTypeFilterVVO1,
        ARNumberAgainstMRNITEM_ItemNameVVO1,
        GoodsinTransit_ChallanNoVVO1,
        SRVDetail_ApproveFilterVVO1,
        SRVDetail_statusfilterVVO1,
        SRVDetail_LocationFilterVVO1,
        DailyStockStatement_LocationFilterVVO1,
        ShortExcessRegister_RepTypeVVO1,
        MonthlyPackingSummary_CategaryCdVVO1,
        AR_UnitVVO1,
        AR_LocationVVO1,
        AR_GROUPVVO1,
        AR_ITEMVVO1,
        AR_AR_NOVVO1,
        AR_SubGroupVVO1,
        Sec_Control_ValuesVVO1,
        Bulk_IssueSlipNoVVO1,
        Bulk_ItemNameVVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int UNITCODE = AttributesEnum.UnitCode.index();
    public static final int GLTYPE = AttributesEnum.GlType.index();
    public static final int FINYEAR = AttributesEnum.FinYear.index();
    public static final int FROMDATE = AttributesEnum.fromDate.index();
    public static final int TODATE = AttributesEnum.toDate.index();
    public static final int GLCODE = AttributesEnum.GlCode.index();
    public static final int LOC = AttributesEnum.LOC.index();
    public static final int CUSTOMER = AttributesEnum.Customer.index();
    public static final int ITEMCD = AttributesEnum.ItemCd.index();
    public static final int GROUPCD = AttributesEnum.GroupCd.index();
    public static final int SUBGROUPCD = AttributesEnum.SubGroupCd.index();
    public static final int LOCWIP = AttributesEnum.LocWip.index();
    public static final int INC_CAN = AttributesEnum.INC_CAN.index();
    public static final int DOCTYPE = AttributesEnum.DocType.index();
    public static final int DAFILTER = AttributesEnum.DAFILTER.index();
    public static final int PONO = AttributesEnum.PoNo.index();
    public static final int CHALLANTYPE = AttributesEnum.ChallanType.index();
    public static final int COLLECTIONCUST = AttributesEnum.CollectionCust.index();
    public static final int BANKRECONCILATION_GL = AttributesEnum.BankReconcilation_GL.index();
    public static final int DEBIT_CREDIT_NOTE_TYPE = AttributesEnum.Debit_Credit_note_Type.index();
    public static final int ASMBLYJC_PROD_CD = AttributesEnum.AsmblyJC_Prod_Cd.index();
    public static final int ASMBLY_JCNO = AttributesEnum.Asmbly_JCNo.index();
    public static final int BOM_PRODUCT_CD = AttributesEnum.BOM_Product_CD.index();
    public static final int WIPLGR_PRCSSFILTER = AttributesEnum.WIPLgr_PrcssFilter.index();
    public static final int WIPLGR_ITEMFILTER = AttributesEnum.WIPLgr_ItemFilter.index();
    public static final int BOMTREE_BOM_PRD_CD = AttributesEnum.BOMTree_BOM_Prd_cd.index();
    public static final int BOMTREE_BATCHQTY = AttributesEnum.BOMTree_Batchqty.index();
    public static final int REQUIREDBATCH = AttributesEnum.RequiredBatch.index();
    public static final int PARTNAMEFILTER = AttributesEnum.PartNameFilter.index();
    public static final int ASSEMBLY_PRD_DTL_PRDCD = AttributesEnum.Assembly_prd_dtl_prdcd.index();
    public static final int BMR_BT_BOMITEM = AttributesEnum.BMR_BT_BOMITEM.index();
    public static final int NON_MOVING_ITEM_PRD = AttributesEnum.Non_Moving_Item_prd.index();
    public static final int NON_MOVING_ITEM_DAY = AttributesEnum.Non_Moving_Item_Day.index();
    public static final int SRVREJECTIONREGISTER_REPTYPE = AttributesEnum.SRVRejectionRegister_RepType.index();
    public static final int STOCKADJUSTMENT_PARTNAME = AttributesEnum.StockAdjustment_PartName.index();
    public static final int PNDINGSRVFORQCVENDORCD = AttributesEnum.PndingSrvForQcVendorCd.index();
    public static final int JOBWORKREGISTER_JWNO = AttributesEnum.Jobworkregister_JWNO.index();
    public static final int PURCHASEINDENT_APPROVEDBY = AttributesEnum.PurchaseIndent_ApprovedBy.index();
    public static final int NATUREOFPURCHASE = AttributesEnum.NatureOfPurchase.index();
    public static final int INTERUNIT = AttributesEnum.InterUnit.index();
    public static final int PENDING_PURCHASE_ORDER_VALIDTILL = AttributesEnum.Pending_Purchase_Order_ValidTill.index();
    public static final int PENDING_PURCHASE_ORDER_APPSTATUS = AttributesEnum.Pending_Purchase_Order_AppStatus.index();
    public static final int PROCSINSPCTION_PRODCD = AttributesEnum.ProcsInspction_ProdCD.index();
    public static final int PROCSINSPCTION_PROCESS = AttributesEnum.ProcsInspction_Process.index();
    public static final int QUALITYINPROCESS_ITEMFILTER = AttributesEnum.QualityInProcess_ITEMFILTER.index();
    public static final int ITEMDETAILAFTERQCITEMCD = AttributesEnum.ItemDetailAfterQcItemCd.index();
    public static final int PENDINGBMRFORQC_BATCHFILTER = AttributesEnum.PendingBMRForQC_BatchFilter.index();
    public static final int LV_P1 = AttributesEnum.LV_p1.index();
    public static final int LV_P2 = AttributesEnum.LV_p2.index();
    public static final int LV_P3 = AttributesEnum.LV_p3.index();
    public static final int LV_P4 = AttributesEnum.LV_p4.index();
    public static final int LV_P5 = AttributesEnum.LV_p5.index();
    public static final int LV_P6 = AttributesEnum.LV_p6.index();
    public static final int SUBLEDGER_UNITCODE = AttributesEnum.SubLedger_UnitCode.index();
    public static final int SUBLEDGERNAMEFILTER = AttributesEnum.SubLedgerNameFilter.index();
    public static final int CHALLAN_NO = AttributesEnum.Challan_No.index();
    public static final int PENDINGTOD28_ITEMCODE = AttributesEnum.PendingToD28_ItemCode.index();
    public static final int WAREHOUSENAME = AttributesEnum.WarehouseName.index();
    public static final int DAILYINVOICE_INVOICENO = AttributesEnum.DailyInvoice_InvoiceNo.index();
    public static final int INVOICEWISESALE_ITEMNAME = AttributesEnum.InvoiceWiseSale_ItemName.index();
    public static final int INTERUNITTRANSIT_UNITCODE = AttributesEnum.InterUnitTransit_UnitCode.index();
    public static final int EINVOICE_INVOICENO = AttributesEnum.EInvoice_InvoiceNo.index();
    public static final int ITEMWISESALE_INVOICETYPE = AttributesEnum.ItemWiseSale_InvoiceType.index();
    public static final int ITEMWISESALE_STOCKTYPE = AttributesEnum.ItemWiseSale_StockType.index();
    public static final int ITEMWISESALE_PRODUCTCODE = AttributesEnum.ItemWiseSale_ProductCode.index();
    public static final int TRFREGISTER_PRODUCTFILTER = AttributesEnum.TRFRegister_ProductFilter.index();
    public static final int BATCHWISEBMRCONSUMPTION_PARTCODE = AttributesEnum.BatchwiseBMRConsumption_partCode.index();
    public static final int BATCHWISEBMRCONSUMPTION_BATCHNO = AttributesEnum.BatchwiseBMRConsumption_BatchNo.index();
    public static final int BATCHWISEBPRCONSUMPTION_PRODUCTNAME =
        AttributesEnum.BatchWiseBPRConsumption_ProductName.index();
    public static final int BATCHWISEBPRCONSUMPTION_BATCHNO = AttributesEnum.BatchWiseBPRConsumption_BatchNo.index();
    public static final int PENDINGJOBCARDFORAPPROVAL_APPROVED =
        AttributesEnum.PendingJobcardForApproval_Approved.index();
    public static final int LOTSTOCK_ITEMTYPE = AttributesEnum.LotStock_ItemType.index();
    public static final int PRODUCTSHORTAGEANDBATCH_PRODUCTNAME =
        AttributesEnum.ProductShortageandBatch_ProductName.index();
    public static final int ITEMWISETOTALINVENTORY_PRODUCTCD = AttributesEnum.ItemWiseTotalInventory_ProductCd.index();
    public static final int REQUISITIONSLIPREGISTER_REQTYPEFILTER =
        AttributesEnum.RequisitionSlipRegister_ReqTypeFilter.index();
    public static final int ARNUMBERAGAINSTMRNITEM_ITEMNAME = AttributesEnum.ARNumberAgainstMRNITEM_ItemName.index();
    public static final int GOODSINTRANSIT_CHALLANNO = AttributesEnum.GoodsinTransit_ChallanNo.index();
    public static final int SRVDETAIL_APPROVEFILTER = AttributesEnum.SRVDetail_ApproveFilter.index();
    public static final int SRVDETAIL_STATUSFILTER = AttributesEnum.SRVDetail_Statusfilter.index();
    public static final int SRVDETAIL_LOCATIONFILTER = AttributesEnum.SRVDetail_LocationFilter.index();
    public static final int DAILYSTOCKSTATEMENT_LOCATIONFILTER =
        AttributesEnum.DailyStockStatement_LocationFilter.index();
    public static final int SHORTEXCESSREGISTER_REPTYPE = AttributesEnum.ShortExcessRegister_RepType.index();
    public static final int MONTHLYPACKINGSUMMARY_CATEGARYCD = AttributesEnum.MonthlyPackingSummary_CategaryCd.index();
    public static final int AR_UNIT = AttributesEnum.AR_Unit.index();
    public static final int AR_LOCATION = AttributesEnum.AR_Location.index();
    public static final int AR_GROUP = AttributesEnum.AR_GROUP.index();
    public static final int AR_ITEM = AttributesEnum.AR_ITEM.index();
    public static final int AR_AR_NO = AttributesEnum.AR_AR_NO.index();
    public static final int AR_SUBGROUP = AttributesEnum.AR_SubGroup.index();
    public static final int REP_TYPE = AttributesEnum.rep_type.index();
    public static final int BULK_ISSUESLIPNO = AttributesEnum.Bulk_IssueSlipNo.index();
    public static final int BULK_ITEMNAME = AttributesEnum.Bulk_ItemName.index();
    public static final int UNITVVO1 = AttributesEnum.UnitVVO1.index();
    public static final int GLCODEVVO2 = AttributesEnum.GlCodeVVO2.index();
    public static final int LOCVVO1 = AttributesEnum.LocVVO1.index();
    public static final int CUSTOMERVVO1 = AttributesEnum.CustomerVVO1.index();
    public static final int GROUPCODEVVO1 = AttributesEnum.GroupCodeVVO1.index();
    public static final int SUBGROUPCODEVVO1 = AttributesEnum.SubGroupCodeVVO1.index();
    public static final int LOCPRODWIPVVO1 = AttributesEnum.LocProdWipVVO1.index();
    public static final int SALEREGISTERDETAILVO1 = AttributesEnum.SaleregisterDetailVO1.index();
    public static final int TESTVVO1 = AttributesEnum.TestVVO1.index();
    public static final int CANCELATIONVVO1 = AttributesEnum.CancelationVVO1.index();
    public static final int FINYEARVVO1 = AttributesEnum.FinYearVVO1.index();
    public static final int ITEMCODEVVO3 = AttributesEnum.ItemCodeVVO3.index();
    public static final int DOCTYPESTATICVALUEVVO1 = AttributesEnum.DocTypeStaticvalueVVO1.index();
    public static final int PONOFILTERVVO1 = AttributesEnum.PONoFILTERVVO1.index();
    public static final int CHALLANTYPEFILTERVVO1 = AttributesEnum.ChallanTypeFilterVVO1.index();
    public static final int COLLECTIONCUSTOMERVVO1 = AttributesEnum.CollectionCustomerVVO1.index();
    public static final int BANKRECONCILIATIONGLVVO1 = AttributesEnum.BankReconciliationGLVVO1.index();
    public static final int DEBITCREDITNOTE_TYPEVVO1 = AttributesEnum.DebitCreditNote_typeVVO1.index();
    public static final int YES_NO_BOTHVVO1 = AttributesEnum.YES_NO_BOTHVVO1.index();
    public static final int GL_TYPEVO1 = AttributesEnum.GL_TypeVO1.index();
    public static final int ASSEMBLYJOBCARD_PRODCODEVVO1 = AttributesEnum.AssemblyJobCard_prodcodeVVO1.index();
    public static final int ASSEMBLYJOBCARD_JCNOVVO1 = AttributesEnum.AssemblyJobCard_JCNoVVO1.index();
    public static final int BOM_PRD_CDVVO1 = AttributesEnum.BOM_PRD_CDVVO1.index();
    public static final int WIPLGR_PROCESSFILTERVVO1 = AttributesEnum.WIPLgr_ProcessFilterVVO1.index();
    public static final int WIPLGR_ITEMFILTERVVO1 = AttributesEnum.WIPLgr_ItemFilterVVO1.index();
    public static final int BOMTREE_PRDCDVVO1 = AttributesEnum.BOMTree_PRDCDVVO1.index();
    public static final int BOM_BATCH_QTYVVO1 = AttributesEnum.Bom_batch_qtyVVO1.index();
    public static final int BOMTREE_BATCH_QTYVVO1 = AttributesEnum.BOMTree_batch_qtyVVO1.index();
    public static final int PARTNAMEFILTERVVO1 = AttributesEnum.PartNameFilterVVO1.index();
    public static final int ASSEMBLY_PRD_DTL_PRDCD1 = AttributesEnum.Assembly_prd_dtl_Prdcd1.index();
    public static final int BMR_BT_BOMITEMVVO1 = AttributesEnum.BMR_BT_BOMITEMVVO1.index();
    public static final int DA_FILTER2 = AttributesEnum.DA_Filter2.index();
    public static final int NON_MOVING_ITEM_PRODUCTVVO1 = AttributesEnum.Non_Moving_Item_ProductVVO1.index();
    public static final int SRVREJECTIONREGISTER_REPTYPEVO1 = AttributesEnum.SRVRejectionRegister_REPTYPEVO1.index();
    public static final int STOCKADJUSTMENT_PARTNAMEVVO1 = AttributesEnum.StockAdjustment_PartNameVVO1.index();
    public static final int PNDINGSRVFORQCVENDORCDVVO1 = AttributesEnum.PndingSRVForQcVendorCdVVO1.index();
    public static final int JOBWORKREGISTERJWNOVVO1 = AttributesEnum.JobworkRegisterJWNOVVO1.index();
    public static final int PURCHASEINDENT_APPROVEDBYVVO1 = AttributesEnum.PurchaseIndent_ApprovedByVVO1.index();
    public static final int PRCHSE_RGISTR_NATUREOFPURCHASEVO1 =
        AttributesEnum.Prchse_Rgistr_NatureOfPurchaseVO1.index();
    public static final int PRCHSE_RGISTR_INTER_UNIT1 = AttributesEnum.Prchse_Rgistr_INTER_UNIT1.index();
    public static final int PENDINGPURCHASEORDERVALIDTILLVVO1 =
        AttributesEnum.PendingPurchaseOrderValidTillVVO1.index();
    public static final int PENDINGPURCHASEORDERAPPSTATUSVVO1 =
        AttributesEnum.PendingPurchaseOrderAppStatusVVO1.index();
    public static final int PROCSINSPCTIONPRODUCTCODEVVO1 = AttributesEnum.ProcsInspctionProductCodeVVO1.index();
    public static final int PROCSINSPCTIONPROCESSVVO1 = AttributesEnum.ProcsInspctionProcessVVO1.index();
    public static final int QUALITYINPROCESS_ITEMFILTERVVO1 = AttributesEnum.QualityInProcess_ITEMFILTERVVO1.index();
    public static final int ITEMDETAILAFTERQC_ITEMCD1 = AttributesEnum.ItemDetailAfterQC_ItemCd1.index();
    public static final int PENDINGBMRFORQC_BATCHFILTERVVO1 = AttributesEnum.PendingBMRForQC_BatchFilterVVO1.index();
    public static final int SUBLEDGER_UNITVVO1 = AttributesEnum.SubLedger_UnitVVO1.index();
    public static final int SUBLEDGERNAMEFILTERVVO1 = AttributesEnum.SubLedgerNameFilterVVO1.index();
    public static final int CHALLAN_NOVVO1 = AttributesEnum.Challan_NoVVO1.index();
    public static final int PENDINGTOD28_ITEMCODEVVO1 = AttributesEnum.PendingToD28_ItemCodeVVO1.index();
    public static final int STOFROMSALE_WAREHOUSENAME1 = AttributesEnum.STOFromSale_WarehouseName1.index();
    public static final int DAILYINVOICE_INVOICENOVVO1 = AttributesEnum.DailyInvoice_InvoiceNoVVO1.index();
    public static final int INVOICEWISESALE_ITEMNAMEVVO1 = AttributesEnum.InvoiceWiseSale_ItemNameVVO1.index();
    public static final int INTERUNITTRANSITREPORT_UNITCODEVVO1 =
        AttributesEnum.InterUnitTransitReport_UnitCodeVVO1.index();
    public static final int EINVOICE_INVOICENOVVO1 = AttributesEnum.EInvoice_InvoiceNoVVO1.index();
    public static final int ITEMWISESALE_INVOICETYPEVVO1 = AttributesEnum.ItemWiseSale_InvoiceTypeVVO1.index();
    public static final int ITEMWISESALE_STOCKTYPEVVO1 = AttributesEnum.ItemWiseSale_StockTypeVVO1.index();
    public static final int ITEMWISESALE_PRODUCTCODEVVO1 = AttributesEnum.ItemWiseSale_ProductCodeVVO1.index();
    public static final int TRFREGISTER_PRODUCTFILTERVO1 = AttributesEnum.TRFRegister_ProductFilterVO1.index();
    public static final int BATCHWISEBMRCONSUMPTION_PARCODEVVO1 =
        AttributesEnum.BatchwiseBMRConsumption_parCodeVVO1.index();
    public static final int BATCHWISEBMRCONSUMPTION_BATCHNOVVO1 =
        AttributesEnum.BatchwiseBMRConsumption_BatchNoVVO1.index();
    public static final int BATCHWISEBPRCONSUMPTION_PRODUCTNAMEVVO1 =
        AttributesEnum.BatchWiseBPRConsumption_ProductNameVVO1.index();
    public static final int BATCHWISEBPRCONSUMPTION_BATCHNOVVO1 =
        AttributesEnum.BatchWiseBPRConsumption_BatchNoVVO1.index();
    public static final int PENDINGJOBCARDFORAPPROVAL_APPROVEDVVO1 =
        AttributesEnum.PendingJobcardForApproval_ApprovedVVO1.index();
    public static final int LOTSTOCK_ITEMTYPEVVO1 = AttributesEnum.LotStock_ItemTypeVVO1.index();
    public static final int PRODUCTSHORTAGEANDBATCHREPORTVO1 = AttributesEnum.ProductShortageandBatchReportVO1.index();
    public static final int PRODUCTSHORTAGEANDBATCH_PRODUCTNAMEVVO1 =
        AttributesEnum.ProductShortageandBatch_ProductNameVVO1.index();
    public static final int ITEMWISETOTALINVENTORY_PRODUCTCDVVO1 =
        AttributesEnum.ItemWiseTotalinventory_ProductCdVVO1.index();
    public static final int REQUISITIONSLIPREGISTER_REQTYPEFILTERVVO1 =
        AttributesEnum.RequisitionSlipRegister_ReqTypeFilterVVO1.index();
    public static final int ARNUMBERAGAINSTMRNITEM_ITEMNAMEVVO1 =
        AttributesEnum.ARNumberAgainstMRNITEM_ItemNameVVO1.index();
    public static final int GOODSINTRANSIT_CHALLANNOVVO1 = AttributesEnum.GoodsinTransit_ChallanNoVVO1.index();
    public static final int SRVDETAIL_APPROVEFILTERVVO1 = AttributesEnum.SRVDetail_ApproveFilterVVO1.index();
    public static final int SRVDETAIL_STATUSFILTERVVO1 = AttributesEnum.SRVDetail_statusfilterVVO1.index();
    public static final int SRVDETAIL_LOCATIONFILTERVVO1 = AttributesEnum.SRVDetail_LocationFilterVVO1.index();
    public static final int DAILYSTOCKSTATEMENT_LOCATIONFILTERVVO1 =
        AttributesEnum.DailyStockStatement_LocationFilterVVO1.index();
    public static final int SHORTEXCESSREGISTER_REPTYPEVVO1 = AttributesEnum.ShortExcessRegister_RepTypeVVO1.index();
    public static final int MONTHLYPACKINGSUMMARY_CATEGARYCDVVO1 =
        AttributesEnum.MonthlyPackingSummary_CategaryCdVVO1.index();
    public static final int AR_UNITVVO1 = AttributesEnum.AR_UnitVVO1.index();
    public static final int AR_LOCATIONVVO1 = AttributesEnum.AR_LocationVVO1.index();
    public static final int AR_GROUPVVO1 = AttributesEnum.AR_GROUPVVO1.index();
    public static final int AR_ITEMVVO1 = AttributesEnum.AR_ITEMVVO1.index();
    public static final int AR_AR_NOVVO1 = AttributesEnum.AR_AR_NOVVO1.index();
    public static final int AR_SUBGROUPVVO1 = AttributesEnum.AR_SubGroupVVO1.index();
    public static final int SEC_CONTROL_VALUESVVO1 = AttributesEnum.Sec_Control_ValuesVVO1.index();
    public static final int BULK_ISSUESLIPNOVVO1 = AttributesEnum.Bulk_IssueSlipNoVVO1.index();
    public static final int BULK_ITEMNAMEVVO1 = AttributesEnum.Bulk_ItemNameVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DummyVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dummy.
     * @return the Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitCode.
     * @return the UnitCode
     */
    public String getUnitCode() {
        return (String) getAttributeInternal(UNITCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitCode.
     * @param value value to set the  UnitCode
     */
    public void setUnitCode(String value) {
        setAttributeInternal(UNITCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GlType.
     * @return the GlType
     */
    public String getGlType() {
        return (String) getAttributeInternal(GLTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GlType.
     * @param value value to set the  GlType
     */
    public void setGlType(String value) {
        setAttributeInternal(GLTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FinYear.
     * @return the FinYear
     */
    public String getFinYear() {
        return (String) getAttributeInternal(FINYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FinYear.
     * @param value value to set the  FinYear
     */
    public void setFinYear(String value) {
        setAttributeInternal(FINYEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute fromDate.
     * @return the fromDate
     */
    public Date getfromDate() {
        return (Date) getAttributeInternal(FROMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute fromDate.
     * @param value value to set the  fromDate
     */
    public void setfromDate(Date value) {
        setAttributeInternal(FROMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute toDate.
     * @return the toDate
     */
    public Date gettoDate() {
        return (Date) getAttributeInternal(TODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute toDate.
     * @param value value to set the  toDate
     */
    public void settoDate(Date value) {
        setAttributeInternal(TODATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GlCode.
     * @return the GlCode
     */
    public String getGlCode() {
        return (String) getAttributeInternal(GLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GlCode.
     * @param value value to set the  GlCode
     */
    public void setGlCode(String value) {
        setAttributeInternal(GLCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LOC.
     * @return the LOC
     */
    public String getLOC() {
        return (String) getAttributeInternal(LOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LOC.
     * @param value value to set the  LOC
     */
    public void setLOC(String value) {
        setAttributeInternal(LOC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customer.
     * @return the Customer
     */
    public String getCustomer() {
        return (String) getAttributeInternal(CUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customer.
     * @param value value to set the  Customer
     */
    public void setCustomer(String value) {
        setAttributeInternal(CUSTOMER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemCd.
     * @return the ItemCd
     */
    public String getItemCd() {
        return (String) getAttributeInternal(ITEMCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemCd.
     * @param value value to set the  ItemCd
     */
    public void setItemCd(String value) {
        setAttributeInternal(ITEMCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupCd.
     * @return the GroupCd
     */
    public String getGroupCd() {
        return (String) getAttributeInternal(GROUPCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupCd.
     * @param value value to set the  GroupCd
     */
    public void setGroupCd(String value) {
        setAttributeInternal(GROUPCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubGroupCd.
     * @return the SubGroupCd
     */
    public String getSubGroupCd() {
        return (String) getAttributeInternal(SUBGROUPCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubGroupCd.
     * @param value value to set the  SubGroupCd
     */
    public void setSubGroupCd(String value) {
        setAttributeInternal(SUBGROUPCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LocWip.
     * @return the LocWip
     */
    public String getLocWip() {
        return (String) getAttributeInternal(LOCWIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LocWip.
     * @param value value to set the  LocWip
     */
    public void setLocWip(String value) {
        setAttributeInternal(LOCWIP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute INC_CAN.
     * @return the INC_CAN
     */
    public String getINC_CAN() {
        return (String) getAttributeInternal(INC_CAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute INC_CAN.
     * @param value value to set the  INC_CAN
     */
    public void setINC_CAN(String value) {
        setAttributeInternal(INC_CAN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocType.
     * @return the DocType
     */
    public String getDocType() {
        return (String) getAttributeInternal(DOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocType.
     * @param value value to set the  DocType
     */
    public void setDocType(String value) {
        setAttributeInternal(DOCTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DAFILTER.
     * @return the DAFILTER
     */
    public String getDAFILTER() {
        return (String) getAttributeInternal(DAFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DAFILTER.
     * @param value value to set the  DAFILTER
     */
    public void setDAFILTER(String value) {
        setAttributeInternal(DAFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoNo.
     * @return the PoNo
     */
    public String getPoNo() {
        return (String) getAttributeInternal(PONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoNo.
     * @param value value to set the  PoNo
     */
    public void setPoNo(String value) {
        setAttributeInternal(PONO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ChallanType.
     * @return the ChallanType
     */
    public String getChallanType() {
        return (String) getAttributeInternal(CHALLANTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ChallanType.
     * @param value value to set the  ChallanType
     */
    public void setChallanType(String value) {
        setAttributeInternal(CHALLANTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CollectionCust.
     * @return the CollectionCust
     */
    public String getCollectionCust() {
        return (String) getAttributeInternal(COLLECTIONCUST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CollectionCust.
     * @param value value to set the  CollectionCust
     */
    public void setCollectionCust(String value) {
        setAttributeInternal(COLLECTIONCUST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankReconcilation_GL.
     * @return the BankReconcilation_GL
     */
    public String getBankReconcilation_GL() {
        return (String) getAttributeInternal(BANKRECONCILATION_GL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BankReconcilation_GL.
     * @param value value to set the  BankReconcilation_GL
     */
    public void setBankReconcilation_GL(String value) {
        setAttributeInternal(BANKRECONCILATION_GL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Debit_Credit_note_Type.
     * @return the Debit_Credit_note_Type
     */
    public String getDebit_Credit_note_Type() {
        return (String) getAttributeInternal(DEBIT_CREDIT_NOTE_TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Debit_Credit_note_Type.
     * @param value value to set the  Debit_Credit_note_Type
     */
    public void setDebit_Credit_note_Type(String value) {
        setAttributeInternal(DEBIT_CREDIT_NOTE_TYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AsmblyJC_Prod_Cd.
     * @return the AsmblyJC_Prod_Cd
     */
    public String getAsmblyJC_Prod_Cd() {
        return (String) getAttributeInternal(ASMBLYJC_PROD_CD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AsmblyJC_Prod_Cd.
     * @param value value to set the  AsmblyJC_Prod_Cd
     */
    public void setAsmblyJC_Prod_Cd(String value) {
        setAttributeInternal(ASMBLYJC_PROD_CD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Asmbly_JCNo.
     * @return the Asmbly_JCNo
     */
    public String getAsmbly_JCNo() {
        return (String) getAttributeInternal(ASMBLY_JCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Asmbly_JCNo.
     * @param value value to set the  Asmbly_JCNo
     */
    public void setAsmbly_JCNo(String value) {
        setAttributeInternal(ASMBLY_JCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BOM_Product_CD.
     * @return the BOM_Product_CD
     */
    public String getBOM_Product_CD() {
        return (String) getAttributeInternal(BOM_PRODUCT_CD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BOM_Product_CD.
     * @param value value to set the  BOM_Product_CD
     */
    public void setBOM_Product_CD(String value) {
        setAttributeInternal(BOM_PRODUCT_CD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WIPLgr_PrcssFilter.
     * @return the WIPLgr_PrcssFilter
     */
    public String getWIPLgr_PrcssFilter() {
        return (String) getAttributeInternal(WIPLGR_PRCSSFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WIPLgr_PrcssFilter.
     * @param value value to set the  WIPLgr_PrcssFilter
     */
    public void setWIPLgr_PrcssFilter(String value) {
        setAttributeInternal(WIPLGR_PRCSSFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WIPLgr_ItemFilter.
     * @return the WIPLgr_ItemFilter
     */
    public String getWIPLgr_ItemFilter() {
        return (String) getAttributeInternal(WIPLGR_ITEMFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WIPLgr_ItemFilter.
     * @param value value to set the  WIPLgr_ItemFilter
     */
    public void setWIPLgr_ItemFilter(String value) {
        setAttributeInternal(WIPLGR_ITEMFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BOMTree_BOM_Prd_cd.
     * @return the BOMTree_BOM_Prd_cd
     */
    public String getBOMTree_BOM_Prd_cd() {
        return (String) getAttributeInternal(BOMTREE_BOM_PRD_CD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BOMTree_BOM_Prd_cd.
     * @param value value to set the  BOMTree_BOM_Prd_cd
     */
    public void setBOMTree_BOM_Prd_cd(String value) {
        setAttributeInternal(BOMTREE_BOM_PRD_CD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BOMTree_Batchqty.
     * @return the BOMTree_Batchqty
     */
    public String getBOMTree_Batchqty() {
        return (String) getAttributeInternal(BOMTREE_BATCHQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BOMTree_Batchqty.
     * @param value value to set the  BOMTree_Batchqty
     */
    public void setBOMTree_Batchqty(String value) {
        setAttributeInternal(BOMTREE_BATCHQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequiredBatch.
     * @return the RequiredBatch
     */
    public String getRequiredBatch() {
        return (String) getAttributeInternal(REQUIREDBATCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequiredBatch.
     * @param value value to set the  RequiredBatch
     */
    public void setRequiredBatch(String value) {
        setAttributeInternal(REQUIREDBATCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartNameFilter.
     * @return the PartNameFilter
     */
    public String getPartNameFilter() {
        return (String) getAttributeInternal(PARTNAMEFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartNameFilter.
     * @param value value to set the  PartNameFilter
     */
    public void setPartNameFilter(String value) {
        setAttributeInternal(PARTNAMEFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Assembly_prd_dtl_prdcd.
     * @return the Assembly_prd_dtl_prdcd
     */
    public String getAssembly_prd_dtl_prdcd() {
        return (String) getAttributeInternal(ASSEMBLY_PRD_DTL_PRDCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Assembly_prd_dtl_prdcd.
     * @param value value to set the  Assembly_prd_dtl_prdcd
     */
    public void setAssembly_prd_dtl_prdcd(String value) {
        setAttributeInternal(ASSEMBLY_PRD_DTL_PRDCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BMR_BT_BOMITEM.
     * @return the BMR_BT_BOMITEM
     */
    public String getBMR_BT_BOMITEM() {
        return (String) getAttributeInternal(BMR_BT_BOMITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BMR_BT_BOMITEM.
     * @param value value to set the  BMR_BT_BOMITEM
     */
    public void setBMR_BT_BOMITEM(String value) {
        setAttributeInternal(BMR_BT_BOMITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Non_Moving_Item_prd.
     * @return the Non_Moving_Item_prd
     */
    public String getNon_Moving_Item_prd() {
        return (String) getAttributeInternal(NON_MOVING_ITEM_PRD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Non_Moving_Item_prd.
     * @param value value to set the  Non_Moving_Item_prd
     */
    public void setNon_Moving_Item_prd(String value) {
        setAttributeInternal(NON_MOVING_ITEM_PRD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Non_Moving_Item_Day.
     * @return the Non_Moving_Item_Day
     */
    public String getNon_Moving_Item_Day() {
        return (String) getAttributeInternal(NON_MOVING_ITEM_DAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Non_Moving_Item_Day.
     * @param value value to set the  Non_Moving_Item_Day
     */
    public void setNon_Moving_Item_Day(String value) {
        setAttributeInternal(NON_MOVING_ITEM_DAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SRVRejectionRegister_RepType.
     * @return the SRVRejectionRegister_RepType
     */
    public String getSRVRejectionRegister_RepType() {
        return (String) getAttributeInternal(SRVREJECTIONREGISTER_REPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SRVRejectionRegister_RepType.
     * @param value value to set the  SRVRejectionRegister_RepType
     */
    public void setSRVRejectionRegister_RepType(String value) {
        setAttributeInternal(SRVREJECTIONREGISTER_REPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StockAdjustment_PartName.
     * @return the StockAdjustment_PartName
     */
    public String getStockAdjustment_PartName() {
        return (String) getAttributeInternal(STOCKADJUSTMENT_PARTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StockAdjustment_PartName.
     * @param value value to set the  StockAdjustment_PartName
     */
    public void setStockAdjustment_PartName(String value) {
        setAttributeInternal(STOCKADJUSTMENT_PARTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PndingSrvForQcVendorCd.
     * @return the PndingSrvForQcVendorCd
     */
    public String getPndingSrvForQcVendorCd() {
        return (String) getAttributeInternal(PNDINGSRVFORQCVENDORCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PndingSrvForQcVendorCd.
     * @param value value to set the  PndingSrvForQcVendorCd
     */
    public void setPndingSrvForQcVendorCd(String value) {
        setAttributeInternal(PNDINGSRVFORQCVENDORCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Jobworkregister_JWNO.
     * @return the Jobworkregister_JWNO
     */
    public String getJobworkregister_JWNO() {
        return (String) getAttributeInternal(JOBWORKREGISTER_JWNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Jobworkregister_JWNO.
     * @param value value to set the  Jobworkregister_JWNO
     */
    public void setJobworkregister_JWNO(String value) {
        setAttributeInternal(JOBWORKREGISTER_JWNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PurchaseIndent_ApprovedBy.
     * @return the PurchaseIndent_ApprovedBy
     */
    public String getPurchaseIndent_ApprovedBy() {
        return (String) getAttributeInternal(PURCHASEINDENT_APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PurchaseIndent_ApprovedBy.
     * @param value value to set the  PurchaseIndent_ApprovedBy
     */
    public void setPurchaseIndent_ApprovedBy(String value) {
        setAttributeInternal(PURCHASEINDENT_APPROVEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NatureOfPurchase.
     * @return the NatureOfPurchase
     */
    public String getNatureOfPurchase() {
        return (String) getAttributeInternal(NATUREOFPURCHASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NatureOfPurchase.
     * @param value value to set the  NatureOfPurchase
     */
    public void setNatureOfPurchase(String value) {
        setAttributeInternal(NATUREOFPURCHASE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InterUnit.
     * @return the InterUnit
     */
    public String getInterUnit() {
        return (String) getAttributeInternal(INTERUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InterUnit.
     * @param value value to set the  InterUnit
     */
    public void setInterUnit(String value) {
        setAttributeInternal(INTERUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Pending_Purchase_Order_ValidTill.
     * @return the Pending_Purchase_Order_ValidTill
     */
    public String getPending_Purchase_Order_ValidTill() {
        return (String) getAttributeInternal(PENDING_PURCHASE_ORDER_VALIDTILL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Pending_Purchase_Order_ValidTill.
     * @param value value to set the  Pending_Purchase_Order_ValidTill
     */
    public void setPending_Purchase_Order_ValidTill(String value) {
        setAttributeInternal(PENDING_PURCHASE_ORDER_VALIDTILL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Pending_Purchase_Order_AppStatus.
     * @return the Pending_Purchase_Order_AppStatus
     */
    public String getPending_Purchase_Order_AppStatus() {
        return (String) getAttributeInternal(PENDING_PURCHASE_ORDER_APPSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Pending_Purchase_Order_AppStatus.
     * @param value value to set the  Pending_Purchase_Order_AppStatus
     */
    public void setPending_Purchase_Order_AppStatus(String value) {
        setAttributeInternal(PENDING_PURCHASE_ORDER_APPSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcsInspction_ProdCD.
     * @return the ProcsInspction_ProdCD
     */
    public String getProcsInspction_ProdCD() {
        return (String) getAttributeInternal(PROCSINSPCTION_PRODCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProcsInspction_ProdCD.
     * @param value value to set the  ProcsInspction_ProdCD
     */
    public void setProcsInspction_ProdCD(String value) {
        setAttributeInternal(PROCSINSPCTION_PRODCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcsInspction_Process.
     * @return the ProcsInspction_Process
     */
    public String getProcsInspction_Process() {
        return (String) getAttributeInternal(PROCSINSPCTION_PROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProcsInspction_Process.
     * @param value value to set the  ProcsInspction_Process
     */
    public void setProcsInspction_Process(String value) {
        setAttributeInternal(PROCSINSPCTION_PROCESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QualityInProcess_ITEMFILTER.
     * @return the QualityInProcess_ITEMFILTER
     */
    public String getQualityInProcess_ITEMFILTER() {
        return (String) getAttributeInternal(QUALITYINPROCESS_ITEMFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QualityInProcess_ITEMFILTER.
     * @param value value to set the  QualityInProcess_ITEMFILTER
     */
    public void setQualityInProcess_ITEMFILTER(String value) {
        setAttributeInternal(QUALITYINPROCESS_ITEMFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemDetailAfterQcItemCd.
     * @return the ItemDetailAfterQcItemCd
     */
    public String getItemDetailAfterQcItemCd() {
        return (String) getAttributeInternal(ITEMDETAILAFTERQCITEMCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemDetailAfterQcItemCd.
     * @param value value to set the  ItemDetailAfterQcItemCd
     */
    public void setItemDetailAfterQcItemCd(String value) {
        setAttributeInternal(ITEMDETAILAFTERQCITEMCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PendingBMRForQC_BatchFilter.
     * @return the PendingBMRForQC_BatchFilter
     */
    public String getPendingBMRForQC_BatchFilter() {
        return (String) getAttributeInternal(PENDINGBMRFORQC_BATCHFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PendingBMRForQC_BatchFilter.
     * @param value value to set the  PendingBMRForQC_BatchFilter
     */
    public void setPendingBMRForQC_BatchFilter(String value) {
        setAttributeInternal(PENDINGBMRFORQC_BATCHFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p1.
     * @return the LV_p1
     */
    public String getLV_p1() {
        return (String) getAttributeInternal(LV_P1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p1.
     * @param value value to set the  LV_p1
     */
    public void setLV_p1(String value) {
        setAttributeInternal(LV_P1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p2.
     * @return the LV_p2
     */
    public String getLV_p2() {
        return (String) getAttributeInternal(LV_P2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p2.
     * @param value value to set the  LV_p2
     */
    public void setLV_p2(String value) {
        setAttributeInternal(LV_P2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p3.
     * @return the LV_p3
     */
    public String getLV_p3() {
        return (String) getAttributeInternal(LV_P3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p3.
     * @param value value to set the  LV_p3
     */
    public void setLV_p3(String value) {
        setAttributeInternal(LV_P3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p4.
     * @return the LV_p4
     */
    public String getLV_p4() {
        return (String) getAttributeInternal(LV_P4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p4.
     * @param value value to set the  LV_p4
     */
    public void setLV_p4(String value) {
        setAttributeInternal(LV_P4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p5.
     * @return the LV_p5
     */
    public String getLV_p5() {
        return (String) getAttributeInternal(LV_P5);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p5.
     * @param value value to set the  LV_p5
     */
    public void setLV_p5(String value) {
        setAttributeInternal(LV_P5, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LV_p6.
     * @return the LV_p6
     */
    public String getLV_p6() {
        return (String) getAttributeInternal(LV_P6);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LV_p6.
     * @param value value to set the  LV_p6
     */
    public void setLV_p6(String value) {
        setAttributeInternal(LV_P6, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubLedger_UnitCode.
     * @return the SubLedger_UnitCode
     */
    public String getSubLedger_UnitCode() {
        return (String) getAttributeInternal(SUBLEDGER_UNITCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubLedger_UnitCode.
     * @param value value to set the  SubLedger_UnitCode
     */
    public void setSubLedger_UnitCode(String value) {
        setAttributeInternal(SUBLEDGER_UNITCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubLedgerNameFilter.
     * @return the SubLedgerNameFilter
     */
    public String getSubLedgerNameFilter() {
        return (String) getAttributeInternal(SUBLEDGERNAMEFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubLedgerNameFilter.
     * @param value value to set the  SubLedgerNameFilter
     */
    public void setSubLedgerNameFilter(String value) {
        setAttributeInternal(SUBLEDGERNAMEFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Challan_No.
     * @return the Challan_No
     */
    public String getChallan_No() {
        return (String) getAttributeInternal(CHALLAN_NO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Challan_No.
     * @param value value to set the  Challan_No
     */
    public void setChallan_No(String value) {
        setAttributeInternal(CHALLAN_NO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PendingToD28_ItemCode.
     * @return the PendingToD28_ItemCode
     */
    public String getPendingToD28_ItemCode() {
        return (String) getAttributeInternal(PENDINGTOD28_ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PendingToD28_ItemCode.
     * @param value value to set the  PendingToD28_ItemCode
     */
    public void setPendingToD28_ItemCode(String value) {
        setAttributeInternal(PENDINGTOD28_ITEMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseName.
     * @return the WarehouseName
     */
    public String getWarehouseName() {
        return (String) getAttributeInternal(WAREHOUSENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseName.
     * @param value value to set the  WarehouseName
     */
    public void setWarehouseName(String value) {
        setAttributeInternal(WAREHOUSENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DailyInvoice_InvoiceNo.
     * @return the DailyInvoice_InvoiceNo
     */
    public String getDailyInvoice_InvoiceNo() {
        return (String) getAttributeInternal(DAILYINVOICE_INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DailyInvoice_InvoiceNo.
     * @param value value to set the  DailyInvoice_InvoiceNo
     */
    public void setDailyInvoice_InvoiceNo(String value) {
        setAttributeInternal(DAILYINVOICE_INVOICENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceWiseSale_ItemName.
     * @return the InvoiceWiseSale_ItemName
     */
    public String getInvoiceWiseSale_ItemName() {
        return (String) getAttributeInternal(INVOICEWISESALE_ITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceWiseSale_ItemName.
     * @param value value to set the  InvoiceWiseSale_ItemName
     */
    public void setInvoiceWiseSale_ItemName(String value) {
        setAttributeInternal(INVOICEWISESALE_ITEMNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InterUnitTransit_UnitCode.
     * @return the InterUnitTransit_UnitCode
     */
    public String getInterUnitTransit_UnitCode() {
        return (String) getAttributeInternal(INTERUNITTRANSIT_UNITCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InterUnitTransit_UnitCode.
     * @param value value to set the  InterUnitTransit_UnitCode
     */
    public void setInterUnitTransit_UnitCode(String value) {
        setAttributeInternal(INTERUNITTRANSIT_UNITCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EInvoice_InvoiceNo.
     * @return the EInvoice_InvoiceNo
     */
    public String getEInvoice_InvoiceNo() {
        return (String) getAttributeInternal(EINVOICE_INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EInvoice_InvoiceNo.
     * @param value value to set the  EInvoice_InvoiceNo
     */
    public void setEInvoice_InvoiceNo(String value) {
        setAttributeInternal(EINVOICE_INVOICENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemWiseSale_InvoiceType.
     * @return the ItemWiseSale_InvoiceType
     */
    public String getItemWiseSale_InvoiceType() {
        return (String) getAttributeInternal(ITEMWISESALE_INVOICETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemWiseSale_InvoiceType.
     * @param value value to set the  ItemWiseSale_InvoiceType
     */
    public void setItemWiseSale_InvoiceType(String value) {
        setAttributeInternal(ITEMWISESALE_INVOICETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemWiseSale_StockType.
     * @return the ItemWiseSale_StockType
     */
    public String getItemWiseSale_StockType() {
        return (String) getAttributeInternal(ITEMWISESALE_STOCKTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemWiseSale_StockType.
     * @param value value to set the  ItemWiseSale_StockType
     */
    public void setItemWiseSale_StockType(String value) {
        setAttributeInternal(ITEMWISESALE_STOCKTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemWiseSale_ProductCode.
     * @return the ItemWiseSale_ProductCode
     */
    public String getItemWiseSale_ProductCode() {
        return (String) getAttributeInternal(ITEMWISESALE_PRODUCTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemWiseSale_ProductCode.
     * @param value value to set the  ItemWiseSale_ProductCode
     */
    public void setItemWiseSale_ProductCode(String value) {
        setAttributeInternal(ITEMWISESALE_PRODUCTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TRFRegister_ProductFilter.
     * @return the TRFRegister_ProductFilter
     */
    public String getTRFRegister_ProductFilter() {
        return (String) getAttributeInternal(TRFREGISTER_PRODUCTFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TRFRegister_ProductFilter.
     * @param value value to set the  TRFRegister_ProductFilter
     */
    public void setTRFRegister_ProductFilter(String value) {
        setAttributeInternal(TRFREGISTER_PRODUCTFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchwiseBMRConsumption_partCode.
     * @return the BatchwiseBMRConsumption_partCode
     */
    public String getBatchwiseBMRConsumption_partCode() {
        return (String) getAttributeInternal(BATCHWISEBMRCONSUMPTION_PARTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BatchwiseBMRConsumption_partCode.
     * @param value value to set the  BatchwiseBMRConsumption_partCode
     */
    public void setBatchwiseBMRConsumption_partCode(String value) {
        setAttributeInternal(BATCHWISEBMRCONSUMPTION_PARTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchwiseBMRConsumption_BatchNo.
     * @return the BatchwiseBMRConsumption_BatchNo
     */
    public String getBatchwiseBMRConsumption_BatchNo() {
        return (String) getAttributeInternal(BATCHWISEBMRCONSUMPTION_BATCHNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BatchwiseBMRConsumption_BatchNo.
     * @param value value to set the  BatchwiseBMRConsumption_BatchNo
     */
    public void setBatchwiseBMRConsumption_BatchNo(String value) {
        setAttributeInternal(BATCHWISEBMRCONSUMPTION_BATCHNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchWiseBPRConsumption_ProductName.
     * @return the BatchWiseBPRConsumption_ProductName
     */
    public String getBatchWiseBPRConsumption_ProductName() {
        return (String) getAttributeInternal(BATCHWISEBPRCONSUMPTION_PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BatchWiseBPRConsumption_ProductName.
     * @param value value to set the  BatchWiseBPRConsumption_ProductName
     */
    public void setBatchWiseBPRConsumption_ProductName(String value) {
        setAttributeInternal(BATCHWISEBPRCONSUMPTION_PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchWiseBPRConsumption_BatchNo.
     * @return the BatchWiseBPRConsumption_BatchNo
     */
    public String getBatchWiseBPRConsumption_BatchNo() {
        return (String) getAttributeInternal(BATCHWISEBPRCONSUMPTION_BATCHNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BatchWiseBPRConsumption_BatchNo.
     * @param value value to set the  BatchWiseBPRConsumption_BatchNo
     */
    public void setBatchWiseBPRConsumption_BatchNo(String value) {
        setAttributeInternal(BATCHWISEBPRCONSUMPTION_BATCHNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PendingJobcardForApproval_Approved.
     * @return the PendingJobcardForApproval_Approved
     */
    public String getPendingJobcardForApproval_Approved() {
        return (String) getAttributeInternal(PENDINGJOBCARDFORAPPROVAL_APPROVED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PendingJobcardForApproval_Approved.
     * @param value value to set the  PendingJobcardForApproval_Approved
     */
    public void setPendingJobcardForApproval_Approved(String value) {
        setAttributeInternal(PENDINGJOBCARDFORAPPROVAL_APPROVED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LotStock_ItemType.
     * @return the LotStock_ItemType
     */
    public String getLotStock_ItemType() {
        return (String) getAttributeInternal(LOTSTOCK_ITEMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LotStock_ItemType.
     * @param value value to set the  LotStock_ItemType
     */
    public void setLotStock_ItemType(String value) {
        setAttributeInternal(LOTSTOCK_ITEMTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductShortageandBatch_ProductName.
     * @return the ProductShortageandBatch_ProductName
     */
    public String getProductShortageandBatch_ProductName() {
        return (String) getAttributeInternal(PRODUCTSHORTAGEANDBATCH_PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductShortageandBatch_ProductName.
     * @param value value to set the  ProductShortageandBatch_ProductName
     */
    public void setProductShortageandBatch_ProductName(String value) {
        setAttributeInternal(PRODUCTSHORTAGEANDBATCH_PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemWiseTotalInventory_ProductCd.
     * @return the ItemWiseTotalInventory_ProductCd
     */
    public String getItemWiseTotalInventory_ProductCd() {
        return (String) getAttributeInternal(ITEMWISETOTALINVENTORY_PRODUCTCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemWiseTotalInventory_ProductCd.
     * @param value value to set the  ItemWiseTotalInventory_ProductCd
     */
    public void setItemWiseTotalInventory_ProductCd(String value) {
        setAttributeInternal(ITEMWISETOTALINVENTORY_PRODUCTCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequisitionSlipRegister_ReqTypeFilter.
     * @return the RequisitionSlipRegister_ReqTypeFilter
     */
    public String getRequisitionSlipRegister_ReqTypeFilter() {
        return (String) getAttributeInternal(REQUISITIONSLIPREGISTER_REQTYPEFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequisitionSlipRegister_ReqTypeFilter.
     * @param value value to set the  RequisitionSlipRegister_ReqTypeFilter
     */
    public void setRequisitionSlipRegister_ReqTypeFilter(String value) {
        setAttributeInternal(REQUISITIONSLIPREGISTER_REQTYPEFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ARNumberAgainstMRNITEM_ItemName.
     * @return the ARNumberAgainstMRNITEM_ItemName
     */
    public String getARNumberAgainstMRNITEM_ItemName() {
        return (String) getAttributeInternal(ARNUMBERAGAINSTMRNITEM_ITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ARNumberAgainstMRNITEM_ItemName.
     * @param value value to set the  ARNumberAgainstMRNITEM_ItemName
     */
    public void setARNumberAgainstMRNITEM_ItemName(String value) {
        setAttributeInternal(ARNUMBERAGAINSTMRNITEM_ITEMNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GoodsinTransit_ChallanNo.
     * @return the GoodsinTransit_ChallanNo
     */
    public String getGoodsinTransit_ChallanNo() {
        return (String) getAttributeInternal(GOODSINTRANSIT_CHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GoodsinTransit_ChallanNo.
     * @param value value to set the  GoodsinTransit_ChallanNo
     */
    public void setGoodsinTransit_ChallanNo(String value) {
        setAttributeInternal(GOODSINTRANSIT_CHALLANNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SRVDetail_ApproveFilter.
     * @return the SRVDetail_ApproveFilter
     */
    public String getSRVDetail_ApproveFilter() {
        return (String) getAttributeInternal(SRVDETAIL_APPROVEFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SRVDetail_ApproveFilter.
     * @param value value to set the  SRVDetail_ApproveFilter
     */
    public void setSRVDetail_ApproveFilter(String value) {
        setAttributeInternal(SRVDETAIL_APPROVEFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SRVDetail_Statusfilter.
     * @return the SRVDetail_Statusfilter
     */
    public String getSRVDetail_Statusfilter() {
        return (String) getAttributeInternal(SRVDETAIL_STATUSFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SRVDetail_Statusfilter.
     * @param value value to set the  SRVDetail_Statusfilter
     */
    public void setSRVDetail_Statusfilter(String value) {
        setAttributeInternal(SRVDETAIL_STATUSFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SRVDetail_LocationFilter.
     * @return the SRVDetail_LocationFilter
     */
    public String getSRVDetail_LocationFilter() {        
        return (String) getAttributeInternal(SRVDETAIL_LOCATIONFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SRVDetail_LocationFilter.
     * @param value value to set the  SRVDetail_LocationFilter
     */
    public void setSRVDetail_LocationFilter(String value) {
        setAttributeInternal(SRVDETAIL_LOCATIONFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DailyStockStatement_LocationFilter.
     * @return the DailyStockStatement_LocationFilter
     */
    public String getDailyStockStatement_LocationFilter() {
        return (String) getAttributeInternal(DAILYSTOCKSTATEMENT_LOCATIONFILTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DailyStockStatement_LocationFilter.
     * @param value value to set the  DailyStockStatement_LocationFilter
     */
    public void setDailyStockStatement_LocationFilter(String value) {
        setAttributeInternal(DAILYSTOCKSTATEMENT_LOCATIONFILTER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShortExcessRegister_RepType.
     * @return the ShortExcessRegister_RepType
     */
    public String getShortExcessRegister_RepType() {
        return (String) getAttributeInternal(SHORTEXCESSREGISTER_REPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShortExcessRegister_RepType.
     * @param value value to set the  ShortExcessRegister_RepType
     */
    public void setShortExcessRegister_RepType(String value) {
        setAttributeInternal(SHORTEXCESSREGISTER_REPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthlyPackingSummary_CategaryCd.
     * @return the MonthlyPackingSummary_CategaryCd
     */
    public String getMonthlyPackingSummary_CategaryCd() {
        return (String) getAttributeInternal(MONTHLYPACKINGSUMMARY_CATEGARYCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthlyPackingSummary_CategaryCd.
     * @param value value to set the  MonthlyPackingSummary_CategaryCd
     */
    public void setMonthlyPackingSummary_CategaryCd(String value) {
        setAttributeInternal(MONTHLYPACKINGSUMMARY_CATEGARYCD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_Unit.
     * @return the AR_Unit
     */
    public String getAR_Unit() {
        return (String) getAttributeInternal(AR_UNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_Unit.
     * @param value value to set the  AR_Unit
     */
    public void setAR_Unit(String value) {
        setAttributeInternal(AR_UNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_Location.
     * @return the AR_Location
     */
    public String getAR_Location() {
        return (String) getAttributeInternal(AR_LOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_Location.
     * @param value value to set the  AR_Location
     */
    public void setAR_Location(String value) {
        setAttributeInternal(AR_LOCATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_GROUP.
     * @return the AR_GROUP
     */
    public String getAR_GROUP() {
        return (String) getAttributeInternal(AR_GROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_GROUP.
     * @param value value to set the  AR_GROUP
     */
    public void setAR_GROUP(String value) {
        setAttributeInternal(AR_GROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_ITEM.
     * @return the AR_ITEM
     */
    public String getAR_ITEM() {
        return (String) getAttributeInternal(AR_ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_ITEM.
     * @param value value to set the  AR_ITEM
     */
    public void setAR_ITEM(String value) {
        setAttributeInternal(AR_ITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_AR_NO.
     * @return the AR_AR_NO
     */
    public String getAR_AR_NO() {
        return (String) getAttributeInternal(AR_AR_NO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_AR_NO.
     * @param value value to set the  AR_AR_NO
     */
    public void setAR_AR_NO(String value) {
        setAttributeInternal(AR_AR_NO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AR_SubGroup.
     * @return the AR_SubGroup
     */
    public String getAR_SubGroup() {
        return (String) getAttributeInternal(AR_SUBGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AR_SubGroup.
     * @param value value to set the  AR_SubGroup
     */
    public void setAR_SubGroup(String value) {
        setAttributeInternal(AR_SUBGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute rep_type.
     * @return the rep_type
     */
    public String getrep_type() {
        return (String) getAttributeInternal(REP_TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute rep_type.
     * @param value value to set the  rep_type
     */
    public void setrep_type(String value) {
        setAttributeInternal(REP_TYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Bulk_IssueSlipNo.
     * @return the Bulk_IssueSlipNo
     */
    public String getBulk_IssueSlipNo() {
        return (String) getAttributeInternal(BULK_ISSUESLIPNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Bulk_IssueSlipNo.
     * @param value value to set the  Bulk_IssueSlipNo
     */
    public void setBulk_IssueSlipNo(String value) {
        setAttributeInternal(BULK_ISSUESLIPNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Bulk_ItemName.
     * @return the Bulk_ItemName
     */
    public String getBulk_ItemName() {
        return (String) getAttributeInternal(BULK_ITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Bulk_ItemName.
     * @param value value to set the  Bulk_ItemName
     */
    public void setBulk_ItemName(String value) {
        setAttributeInternal(BULK_ITEMNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UnitVVO1.
     */
    public RowSet getUnitVVO1() {
        return (RowSet) getAttributeInternal(UNITVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GlCodeVVO2.
     */
    public RowSet getGlCodeVVO2() {
        return (RowSet) getAttributeInternal(GLCODEVVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocVVO1.
     */
    public RowSet getLocVVO1() {
        return (RowSet) getAttributeInternal(LOCVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerVVO1.
     */
    public RowSet getCustomerVVO1() {
        return (RowSet) getAttributeInternal(CUSTOMERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupCodeVVO1.
     */
    public RowSet getGroupCodeVVO1() {
        return (RowSet) getAttributeInternal(GROUPCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubGroupCodeVVO1.
     */
    public RowSet getSubGroupCodeVVO1() {
        return (RowSet) getAttributeInternal(SUBGROUPCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocProdWipVVO1.
     */
    public RowSet getLocProdWipVVO1() {
        return (RowSet) getAttributeInternal(LOCPRODWIPVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SaleregisterDetailVO1.
     */
    public RowSet getSaleregisterDetailVO1() {
        return (RowSet) getAttributeInternal(SALEREGISTERDETAILVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TestVVO1.
     */
    public RowSet getTestVVO1() {
        return (RowSet) getAttributeInternal(TESTVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CancelationVVO1.
     */
    public RowSet getCancelationVVO1() {
        return (RowSet) getAttributeInternal(CANCELATIONVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FinYearVVO1.
     */
    public RowSet getFinYearVVO1() {
        return (RowSet) getAttributeInternal(FINYEARVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemCodeVVO3.
     */
    public RowSet getItemCodeVVO3() {
        return (RowSet) getAttributeInternal(ITEMCODEVVO3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DocTypeStaticvalueVVO1.
     */
    public RowSet getDocTypeStaticvalueVVO1() {
        return (RowSet) getAttributeInternal(DOCTYPESTATICVALUEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PONoFILTERVVO1.
     */
    public RowSet getPONoFILTERVVO1() {
        return (RowSet) getAttributeInternal(PONOFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ChallanTypeFilterVVO1.
     */
    public RowSet getChallanTypeFilterVVO1() {
        return (RowSet) getAttributeInternal(CHALLANTYPEFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CollectionCustomerVVO1.
     */
    public RowSet getCollectionCustomerVVO1() {
        return (RowSet) getAttributeInternal(COLLECTIONCUSTOMERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BankReconciliationGLVVO1.
     */
    public RowSet getBankReconciliationGLVVO1() {
        return (RowSet) getAttributeInternal(BANKRECONCILIATIONGLVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DebitCreditNote_typeVVO1.
     */
    public RowSet getDebitCreditNote_typeVVO1() {
        return (RowSet) getAttributeInternal(DEBITCREDITNOTE_TYPEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YES_NO_BOTHVVO1.
     */
    public RowSet getYES_NO_BOTHVVO1() {
        return (RowSet) getAttributeInternal(YES_NO_BOTHVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GL_TypeVO1.
     */
    public RowSet getGL_TypeVO1() {
        return (RowSet) getAttributeInternal(GL_TYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AssemblyJobCard_prodcodeVVO1.
     */
    public RowSet getAssemblyJobCard_prodcodeVVO1() {
        return (RowSet) getAttributeInternal(ASSEMBLYJOBCARD_PRODCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AssemblyJobCard_JCNoVVO1.
     */
    public RowSet getAssemblyJobCard_JCNoVVO1() {
        return (RowSet) getAttributeInternal(ASSEMBLYJOBCARD_JCNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BOM_PRD_CDVVO1.
     */
    public RowSet getBOM_PRD_CDVVO1() {
        return (RowSet) getAttributeInternal(BOM_PRD_CDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WIPLgr_ProcessFilterVVO1.
     */
    public RowSet getWIPLgr_ProcessFilterVVO1() {
        return (RowSet) getAttributeInternal(WIPLGR_PROCESSFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WIPLgr_ItemFilterVVO1.
     */
    public RowSet getWIPLgr_ItemFilterVVO1() {
        return (RowSet) getAttributeInternal(WIPLGR_ITEMFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BOMTree_PRDCDVVO1.
     */
    public RowSet getBOMTree_PRDCDVVO1() {
        return (RowSet) getAttributeInternal(BOMTREE_PRDCDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Bom_batch_qtyVVO1.
     */
    public RowSet getBom_batch_qtyVVO1() {
        return (RowSet) getAttributeInternal(BOM_BATCH_QTYVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BOMTree_batch_qtyVVO1.
     */
    public RowSet getBOMTree_batch_qtyVVO1() {
        return (RowSet) getAttributeInternal(BOMTREE_BATCH_QTYVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartNameFilterVVO1.
     */
    public RowSet getPartNameFilterVVO1() {
        return (RowSet) getAttributeInternal(PARTNAMEFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Assembly_prd_dtl_Prdcd1.
     */
    public RowSet getAssembly_prd_dtl_Prdcd1() {
        return (RowSet) getAttributeInternal(ASSEMBLY_PRD_DTL_PRDCD1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BMR_BT_BOMITEMVVO1.
     */
    public RowSet getBMR_BT_BOMITEMVVO1() {
        return (RowSet) getAttributeInternal(BMR_BT_BOMITEMVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DA_Filter2.
     */
    public RowSet getDA_Filter2() {
        return (RowSet) getAttributeInternal(DA_FILTER2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Non_Moving_Item_ProductVVO1.
     */
    public RowSet getNon_Moving_Item_ProductVVO1() {
        return (RowSet) getAttributeInternal(NON_MOVING_ITEM_PRODUCTVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SRVRejectionRegister_REPTYPEVO1.
     */
    public RowSet getSRVRejectionRegister_REPTYPEVO1() {
        return (RowSet) getAttributeInternal(SRVREJECTIONREGISTER_REPTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StockAdjustment_PartNameVVO1.
     */
    public RowSet getStockAdjustment_PartNameVVO1() {
        return (RowSet) getAttributeInternal(STOCKADJUSTMENT_PARTNAMEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PndingSRVForQcVendorCdVVO1.
     */
    public RowSet getPndingSRVForQcVendorCdVVO1() {
        return (RowSet) getAttributeInternal(PNDINGSRVFORQCVENDORCDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> JobworkRegisterJWNOVVO1.
     */
    public RowSet getJobworkRegisterJWNOVVO1() {
        return (RowSet) getAttributeInternal(JOBWORKREGISTERJWNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PurchaseIndent_ApprovedByVVO1.
     */
    public RowSet getPurchaseIndent_ApprovedByVVO1() {
        return (RowSet) getAttributeInternal(PURCHASEINDENT_APPROVEDBYVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Prchse_Rgistr_NatureOfPurchaseVO1.
     */
    public RowSet getPrchse_Rgistr_NatureOfPurchaseVO1() {
        return (RowSet) getAttributeInternal(PRCHSE_RGISTR_NATUREOFPURCHASEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Prchse_Rgistr_INTER_UNIT1.
     */
    public RowSet getPrchse_Rgistr_INTER_UNIT1() {
        return (RowSet) getAttributeInternal(PRCHSE_RGISTR_INTER_UNIT1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PendingPurchaseOrderValidTillVVO1.
     */
    public RowSet getPendingPurchaseOrderValidTillVVO1() {
        return (RowSet) getAttributeInternal(PENDINGPURCHASEORDERVALIDTILLVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PendingPurchaseOrderAppStatusVVO1.
     */
    public RowSet getPendingPurchaseOrderAppStatusVVO1() {
        return (RowSet) getAttributeInternal(PENDINGPURCHASEORDERAPPSTATUSVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProcsInspctionProductCodeVVO1.
     */
    public RowSet getProcsInspctionProductCodeVVO1() {
        return (RowSet) getAttributeInternal(PROCSINSPCTIONPRODUCTCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProcsInspctionProcessVVO1.
     */
    public RowSet getProcsInspctionProcessVVO1() {
        return (RowSet) getAttributeInternal(PROCSINSPCTIONPROCESSVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> QualityInProcess_ITEMFILTERVVO1.
     */
    public RowSet getQualityInProcess_ITEMFILTERVVO1() {
        return (RowSet) getAttributeInternal(QUALITYINPROCESS_ITEMFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemDetailAfterQC_ItemCd1.
     */
    public RowSet getItemDetailAfterQC_ItemCd1() {
        return (RowSet) getAttributeInternal(ITEMDETAILAFTERQC_ITEMCD1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PendingBMRForQC_BatchFilterVVO1.
     */
    public RowSet getPendingBMRForQC_BatchFilterVVO1() {
        return (RowSet) getAttributeInternal(PENDINGBMRFORQC_BATCHFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubLedger_UnitVVO1.
     */
    public RowSet getSubLedger_UnitVVO1() {
        return (RowSet) getAttributeInternal(SUBLEDGER_UNITVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubLedgerNameFilterVVO1.
     */
    public RowSet getSubLedgerNameFilterVVO1() {
        return (RowSet) getAttributeInternal(SUBLEDGERNAMEFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Challan_NoVVO1.
     */
    public RowSet getChallan_NoVVO1() {
        return (RowSet) getAttributeInternal(CHALLAN_NOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PendingToD28_ItemCodeVVO1.
     */
    public RowSet getPendingToD28_ItemCodeVVO1() {
        return (RowSet) getAttributeInternal(PENDINGTOD28_ITEMCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> STOFromSale_WarehouseName1.
     */
    public RowSet getSTOFromSale_WarehouseName1() {
        return (RowSet) getAttributeInternal(STOFROMSALE_WAREHOUSENAME1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DailyInvoice_InvoiceNoVVO1.
     */
    public RowSet getDailyInvoice_InvoiceNoVVO1() {
        return (RowSet) getAttributeInternal(DAILYINVOICE_INVOICENOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvoiceWiseSale_ItemNameVVO1.
     */
    public RowSet getInvoiceWiseSale_ItemNameVVO1() {
        return (RowSet) getAttributeInternal(INVOICEWISESALE_ITEMNAMEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InterUnitTransitReport_UnitCodeVVO1.
     */
    public RowSet getInterUnitTransitReport_UnitCodeVVO1() {
        return (RowSet) getAttributeInternal(INTERUNITTRANSITREPORT_UNITCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EInvoice_InvoiceNoVVO1.
     */
    public RowSet getEInvoice_InvoiceNoVVO1() {
        return (RowSet) getAttributeInternal(EINVOICE_INVOICENOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemWiseSale_InvoiceTypeVVO1.
     */
    public RowSet getItemWiseSale_InvoiceTypeVVO1() {
        return (RowSet) getAttributeInternal(ITEMWISESALE_INVOICETYPEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemWiseSale_StockTypeVVO1.
     */
    public RowSet getItemWiseSale_StockTypeVVO1() {
        return (RowSet) getAttributeInternal(ITEMWISESALE_STOCKTYPEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemWiseSale_ProductCodeVVO1.
     */
    public RowSet getItemWiseSale_ProductCodeVVO1() {
        return (RowSet) getAttributeInternal(ITEMWISESALE_PRODUCTCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TRFRegister_ProductFilterVO1.
     */
    public RowSet getTRFRegister_ProductFilterVO1() {
        return (RowSet) getAttributeInternal(TRFREGISTER_PRODUCTFILTERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BatchwiseBMRConsumption_parCodeVVO1.
     */
    public RowSet getBatchwiseBMRConsumption_parCodeVVO1() {
        return (RowSet) getAttributeInternal(BATCHWISEBMRCONSUMPTION_PARCODEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BatchwiseBMRConsumption_BatchNoVVO1.
     */
    public RowSet getBatchwiseBMRConsumption_BatchNoVVO1() {
        return (RowSet) getAttributeInternal(BATCHWISEBMRCONSUMPTION_BATCHNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BatchWiseBPRConsumption_ProductNameVVO1.
     */
    public RowSet getBatchWiseBPRConsumption_ProductNameVVO1() {
        return (RowSet) getAttributeInternal(BATCHWISEBPRCONSUMPTION_PRODUCTNAMEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BatchWiseBPRConsumption_BatchNoVVO1.
     */
    public RowSet getBatchWiseBPRConsumption_BatchNoVVO1() {
        return (RowSet) getAttributeInternal(BATCHWISEBPRCONSUMPTION_BATCHNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PendingJobcardForApproval_ApprovedVVO1.
     */
    public RowSet getPendingJobcardForApproval_ApprovedVVO1() {
        return (RowSet) getAttributeInternal(PENDINGJOBCARDFORAPPROVAL_APPROVEDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LotStock_ItemTypeVVO1.
     */
    public RowSet getLotStock_ItemTypeVVO1() {
        return (RowSet) getAttributeInternal(LOTSTOCK_ITEMTYPEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductShortageandBatchReportVO1.
     */
    public RowSet getProductShortageandBatchReportVO1() {
        return (RowSet) getAttributeInternal(PRODUCTSHORTAGEANDBATCHREPORTVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductShortageandBatch_ProductNameVVO1.
     */
    public RowSet getProductShortageandBatch_ProductNameVVO1() {
        return (RowSet) getAttributeInternal(PRODUCTSHORTAGEANDBATCH_PRODUCTNAMEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemWiseTotalinventory_ProductCdVVO1.
     */
    public RowSet getItemWiseTotalinventory_ProductCdVVO1() {
        return (RowSet) getAttributeInternal(ITEMWISETOTALINVENTORY_PRODUCTCDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RequisitionSlipRegister_ReqTypeFilterVVO1.
     */
    public RowSet getRequisitionSlipRegister_ReqTypeFilterVVO1() {
        return (RowSet) getAttributeInternal(REQUISITIONSLIPREGISTER_REQTYPEFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ARNumberAgainstMRNITEM_ItemNameVVO1.
     */
    public RowSet getARNumberAgainstMRNITEM_ItemNameVVO1() {
        return (RowSet) getAttributeInternal(ARNUMBERAGAINSTMRNITEM_ITEMNAMEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GoodsinTransit_ChallanNoVVO1.
     */
    public RowSet getGoodsinTransit_ChallanNoVVO1() {
        return (RowSet) getAttributeInternal(GOODSINTRANSIT_CHALLANNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SRVDetail_ApproveFilterVVO1.
     */
    public RowSet getSRVDetail_ApproveFilterVVO1() {
        return (RowSet) getAttributeInternal(SRVDETAIL_APPROVEFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SRVDetail_statusfilterVVO1.
     */
    public RowSet getSRVDetail_statusfilterVVO1() {
        return (RowSet) getAttributeInternal(SRVDETAIL_STATUSFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SRVDetail_LocationFilterVVO1.
     */
    public RowSet getSRVDetail_LocationFilterVVO1() {
        return (RowSet) getAttributeInternal(SRVDETAIL_LOCATIONFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DailyStockStatement_LocationFilterVVO1.
     */
    public RowSet getDailyStockStatement_LocationFilterVVO1() {
        return (RowSet) getAttributeInternal(DAILYSTOCKSTATEMENT_LOCATIONFILTERVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShortExcessRegister_RepTypeVVO1.
     */
    public RowSet getShortExcessRegister_RepTypeVVO1() {
        return (RowSet) getAttributeInternal(SHORTEXCESSREGISTER_REPTYPEVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MonthlyPackingSummary_CategaryCdVVO1.
     */
    public RowSet getMonthlyPackingSummary_CategaryCdVVO1() {
        return (RowSet) getAttributeInternal(MONTHLYPACKINGSUMMARY_CATEGARYCDVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_UnitVVO1.
     */
    public RowSet getAR_UnitVVO1() {
        return (RowSet) getAttributeInternal(AR_UNITVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_LocationVVO1.
     */
    public RowSet getAR_LocationVVO1() {
        return (RowSet) getAttributeInternal(AR_LOCATIONVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_GROUPVVO1.
     */
    public RowSet getAR_GROUPVVO1() {
        return (RowSet) getAttributeInternal(AR_GROUPVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_ITEMVVO1.
     */
    public RowSet getAR_ITEMVVO1() {
        return (RowSet) getAttributeInternal(AR_ITEMVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_AR_NOVVO1.
     */
    public RowSet getAR_AR_NOVVO1() {
        return (RowSet) getAttributeInternal(AR_AR_NOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AR_SubGroupVVO1.
     */
    public RowSet getAR_SubGroupVVO1() {
        return (RowSet) getAttributeInternal(AR_SUBGROUPVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Sec_Control_ValuesVVO1.
     */
    public RowSet getSec_Control_ValuesVVO1() {
        return (RowSet) getAttributeInternal(SEC_CONTROL_VALUESVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Bulk_IssueSlipNoVVO1.
     */
    public RowSet getBulk_IssueSlipNoVVO1() {
        return (RowSet) getAttributeInternal(BULK_ISSUESLIPNOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Bulk_ItemNameVVO1.
     */
    public RowSet getBulk_ItemNameVVO1() {
        return (RowSet) getAttributeInternal(BULK_ITEMNAMEVVO1);
    }
}

